[tool.black]
line-length = 88
target-version = ['py38']
include = '\.pyi?$'
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
^/docs
'''

[tool.pylint]
max-line-length = 88
disable = [
    "C0111",  # missing-docstring
    "C0103",  # invalid-name
    "C0330",  # bad-continuation
    "C0326",  # bad-whitespace
    "W0511",  # fixme
    "R0903",  # too-few-public-methods
    "R0913",  # too-many-arguments
    "R0914",  # too-many-locals
]
ignore = ["CVS", ".git", ".pytest_cache", "__pycache__", "docs"]
ignore-patterns = ["^\\.#"]
good-names = ["i", "j", "k", "ex", "Run", "_", "fp", "id"]

[tool.pylint.messages_control]
disable = [
    "C0111",  # missing-docstring
    "C0103",  # invalid-name
    "C0330",  # bad-continuation
    "C0326",  # bad-whitespace
]

[tool.pylint.format]
max-line-length = 88
max-module-lines = 1000
indent-after-paren = 4

[tool.pylint.basic]
good-names = ["i", "j", "k", "ex", "Run", "_", "fp", "id"]
bad-names = ["foo", "bar", "baz", "toto", "tutu", "tata"]
name-group = []
include-naming-hint = true
function-rgx = "[a-z_][a-z0-9_]{2,30}$"
variable-rgx = "[a-z_][a-z0-9_]{2,30}$"
const-rgx = "(([A-Z_][A-Z0-9_]*)|(__.*__))$"
attr-rgx = "[a-z_][a-z0-9_]{2,30}$"
argument-rgx = "[a-z_][a-z0-9_]{2,30}$"
class-attribute-rgx = "([A-Za-z_][A-Za-z0-9_]{2,30}|(__.*__))$"
inlinevar-rgx = "[A-Za-z_][A-Za-z0-9_]*$"
class-rgx = "[A-Z_][a-zA-Z0-9]+$"
module-rgx = "(([a-z_][a-z0-9_]*)|([A-Z][a-zA-Z0-9]+))$"
method-rgx = "[a-z_][a-z0-9_]{2,30}$"
no-docstring-rgx = "^_"
docstring-min-length = -1

[tool.pylint.similarities]
min-similarity-lines = 4
ignore-comments = true
ignore-docstrings = true
ignore-imports = true

[tool.pylint.miscellaneous]
notes = ["FIXME", "XXX", "TODO"]

[tool.pylint.typecheck]
ignore-mixin-members = true
ignored-classes = ["optparse.Values", "thread._local", "_thread._local"]
generated-members = ["numpy.*", "torch.*"]

[tool.pylint.variables]
init-import = false
dummy-variables-rgx = "_$|dummy"
additional-builtins = []

[tool.pylint.classes]
ignore-iface-methods = ["isImplementedBy", "deferred", "extends", "names", "namesAndDescriptions", "queryDescriptionFor", "getBases", "getDescriptionFor", "getDoc", "getName", "getTaggedValue", "getTaggedValueTags", "isEqualOrExtendedBy", "setTaggedValue", "isImplementedByInstancesOf", "adaptWith", "is_implemented_by"]
defining-attr-methods = ["__init__", "__new__", "setUp"]
valid-classmethod-first-arg = ["cls"]
valid-metaclass-classmethod-first-arg = ["cls"]

[tool.pylint.design]
max-args = 5
max-locals = 15
max-returns = 6
max-branches = 12
max-statements = 50
max-parents = 7
max-attributes = 7
min-public-methods = 2
max-public-methods = 20

[tool.pylint.imports]
deprecated-modules = ["regsub", "TERMIOS", "Bastion", "rexec"]
import-graph = ""
ext-import-graph = ""
int-import-graph = ""

[tool.pylint.exceptions]
overgeneral-exceptions = ["Exception"] 